package Vistas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuJFrame
     */
    public PantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);// centrado
        setExtendedState(PantallaPrincipal.MAXIMIZED_BOTH); // inicia Maximizada
        setTitle("Sistema de Gestión de Turnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCreatePaciente = new javax.swing.JMenuItem();
        jMenuIUpdatePaciente = new javax.swing.JMenuItem();
        jMenuDeletePaciente = new javax.swing.JMenuItem();
        jMenuItemSelectPaciente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemRegistrarEmpleado = new javax.swing.JMenuItem();
        itemActualizarEmpleado = new javax.swing.JMenuItem();
        itemBuscarEmpleado = new javax.swing.JMenuItem();
        itemEliminarEmpleado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAgendarTurno = new javax.swing.JMenuItem();
        itemReagendarTurno = new javax.swing.JMenuItem();
        itemEliminarTurno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        itemCrearUsuario = new javax.swing.JMenuItem();
        itemModificarUsuario = new javax.swing.JMenuItem();
        itemEliminarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Paciente.png"))); // NOI18N
        jMenu1.setText("Paciente");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItemCreatePaciente.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItemCreatePaciente.setText("Nuevo Paciente");
        jMenuItemCreatePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreatePacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCreatePaciente);

        jMenuIUpdatePaciente.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuIUpdatePaciente.setText("Modificar Paciente");
        jMenuIUpdatePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIUpdatePacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIUpdatePaciente);

        jMenuDeletePaciente.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuDeletePaciente.setText("Eliminar Paciente");
        jMenuDeletePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeletePacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDeletePaciente);

        jMenuItemSelectPaciente.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItemSelectPaciente.setText("Consultar Paciente");
        jMenuItemSelectPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSelectPaciente);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doctor.png"))); // NOI18N
        jMenu2.setText("Empleado");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        itemRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemRegistrarEmpleado.setText("Registrar Empleado");
        itemRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemRegistrarEmpleadoMouseClicked(evt);
            }
        });
        itemRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(itemRegistrarEmpleado);

        itemActualizarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemActualizarEmpleado.setText("Actualizar Empleado");
        itemActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(itemActualizarEmpleado);

        itemBuscarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemBuscarEmpleado.setText("Buscar Empleado");
        itemBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(itemBuscarEmpleado);

        itemEliminarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemEliminarEmpleado.setText("Eliminar Empleado");
        itemEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(itemEliminarEmpleado);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/turno.png"))); // NOI18N
        jMenu3.setText("Turno");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        itemAgendarTurno.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemAgendarTurno.setText("Agendar Turno");
        itemAgendarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgendarTurnoActionPerformed(evt);
            }
        });
        jMenu3.add(itemAgendarTurno);

        itemReagendarTurno.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemReagendarTurno.setText("Reagendar Tunro");
        itemReagendarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReagendarTurnoActionPerformed(evt);
            }
        });
        jMenu3.add(itemReagendarTurno);

        itemEliminarTurno.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemEliminarTurno.setText("Eliminar Turno");
        jMenu3.add(itemEliminarTurno);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        jMenu4.setText("Reporte");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem11.setText("Generar Reporte");
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/admin.png"))); // NOI18N
        jMenu5.setText("Administración");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu11.setText("Administración de Usuarios");
        jMenu11.setFocusable(false);
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        itemCrearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemCrearUsuario.setText("Crear Usuario");
        itemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu11.add(itemCrearUsuario);

        itemModificarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemModificarUsuario.setText("Modificar Usuario");
        itemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu11.add(itemModificarUsuario);

        itemEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemEliminarUsuario.setText("Eliminar Usuario");
        itemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu11.add(itemEliminarUsuario);

        jMenu5.add(jMenu11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegistrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemRegistrarEmpleadoMouseClicked

    }//GEN-LAST:event_itemRegistrarEmpleadoMouseClicked

    private void itemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarEmpleadoActionPerformed
        RegistrarEmpleado re = new RegistrarEmpleado();
        re.setVisible(true);
    }//GEN-LAST:event_itemRegistrarEmpleadoActionPerformed

    private void itemActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarEmpleadoActionPerformed
        ActualizarEmpleado ae = new ActualizarEmpleado();
        ae.setVisible(true);
    }//GEN-LAST:event_itemActualizarEmpleadoActionPerformed

    private void itemBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEmpleadoActionPerformed
        BuscarEmpleado be = new BuscarEmpleado();
        be.setVisible(true);
    }//GEN-LAST:event_itemBuscarEmpleadoActionPerformed

    private void itemEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEmpleadoActionPerformed
        EliminarEmpleado ee = new EliminarEmpleado();
        ee.setVisible(true);
    }//GEN-LAST:event_itemEliminarEmpleadoActionPerformed

    private void itemAgendarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgendarTurnoActionPerformed
        AgendarTurno at = new AgendarTurno();
        at.setVisible(true);
    }//GEN-LAST:event_itemAgendarTurnoActionPerformed

    private void itemReagendarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReagendarTurnoActionPerformed
       ReAgendarTurno rt = new ReAgendarTurno();
       rt.setVisible(true);
    }//GEN-LAST:event_itemReagendarTurnoActionPerformed

    private void jMenuDeletePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeletePacienteActionPerformed
        // TODO add your handling code here:
       registrarPacienteJFrame rp = new registrarPacienteJFrame("Eliminar");
       rp.setVisible(true);
    }//GEN-LAST:event_jMenuDeletePacienteActionPerformed

    private void jMenuIUpdatePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIUpdatePacienteActionPerformed
        // TODO add your handling code here:
       registrarPacienteJFrame rp = new registrarPacienteJFrame("Actualizar");
       rp.setVisible(true);
    }//GEN-LAST:event_jMenuIUpdatePacienteActionPerformed

    private void jMenuItemSelectPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectPacienteActionPerformed
        // TODO add your handling code here:
        pacientesListJFrame pl = new pacientesListJFrame();
        pl.setVisible(true);
    }//GEN-LAST:event_jMenuItemSelectPacienteActionPerformed

    private void jMenuItemCreatePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreatePacienteActionPerformed
        // TODO add your handling code here:        
       registrarPacienteJFrame rp = new registrarPacienteJFrame("Ingresar");
       rp.setVisible(true);
    }//GEN-LAST:event_jMenuItemCreatePacienteActionPerformed

    private void itemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearUsuarioActionPerformed
            CrearUsuario cu = new CrearUsuario();
            cu.setVisible(true);
    }//GEN-LAST:event_itemCrearUsuarioActionPerformed

    private void itemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarUsuarioActionPerformed
            ModificarUsuario mu = new ModificarUsuario();
            mu.setVisible(true);
    }//GEN-LAST:event_itemModificarUsuarioActionPerformed

    private void itemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarUsuarioActionPerformed
            EliminarUsuario eu = new EliminarUsuario();
            eu.setVisible(true);
    }//GEN-LAST:event_itemEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemActualizarEmpleado;
    private javax.swing.JMenuItem itemAgendarTurno;
    private javax.swing.JMenuItem itemBuscarEmpleado;
    private javax.swing.JMenuItem itemCrearUsuario;
    private javax.swing.JMenuItem itemEliminarEmpleado;
    private javax.swing.JMenuItem itemEliminarTurno;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemModificarUsuario;
    private javax.swing.JMenuItem itemReagendarTurno;
    private javax.swing.JMenuItem itemRegistrarEmpleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDeletePaciente;
    private javax.swing.JMenuItem jMenuIUpdatePaciente;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItemCreatePaciente;
    private javax.swing.JMenuItem jMenuItemSelectPaciente;
    // End of variables declaration//GEN-END:variables
}
