
package Vistas;

import Controlador.Conexion;
import Modelo.Paciente;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class registrarPacienteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form nuevoPacienteJFrame
     */
    public registrarPacienteJFrame() {
        initComponents();
        setLocationRelativeTo(null);// centrado
        setResizable(false); // impide maximizar
    }
    
    public registrarPacienteJFrame(String opcion) {
        initComponents();
        btnAceptar.setText(opcion);
        switch(opcion){
            case "IngresarPaciente":
                setTitle("Registrar Paciente");
                
                
                
                break;
            default:
                break;
        }
    }
    //// IMPLEMENTACION DE METODOS PARA MANEJAR EL FORMULARO ////
    Paciente nuevoPaciente = new Paciente();
    Conexion miConexion = new Conexion();
    
    public void guardarDatosEmpleado(){
        
        nuevoPaciente.setCedulaPaciente(txtCedulaPaciente.getText().toString().trim());
        nuevoPaciente.setpNombrePaciente(txtPNombrePaciente.getText().toString().trim());
        nuevoPaciente.setsNombrePaciente(txtSNombrePaciente.getText().toString().trim());
        nuevoPaciente.setpApellidoPaciente(txtPApellidoPaciente.getText().toString().trim());
        nuevoPaciente.setsApellidoPaciente(txtSApellidoPaciente.getText().toString().trim());
        nuevoPaciente.setpTelefonoPaciente(txtPTelefonoPaciente.getText().toString().trim());
        nuevoPaciente.setsTelefonoPaciente(txtSTelefonoPaciente.getText().toString().trim());
        nuevoPaciente.setDireccionPaciente(txtDireccionPaciente.getText().toString().trim());
        nuevoPaciente.setEmaiPaciente(txtEmailPaciente.getText().toString().trim());
        
        
        if(String.valueOf(nuevoPaciente.getCedulaPaciente()).compareTo("")==0 || 
           String.valueOf(nuevoPaciente.getpNombrePaciente()).compareTo("")==0 ||
           String.valueOf(nuevoPaciente.getpApellidoPaciente()).compareTo("")==0 ||
           String.valueOf(nuevoPaciente.getpTelefonoPaciente()).compareTo("")==0 ||
           String.valueOf(nuevoPaciente.getDireccionPaciente()).compareTo("")==0 ||
           String.valueOf(nuevoPaciente.getEmaiPaciente()).compareTo("")==0){
           JOptionPane.showMessageDialog(null, "Error - Uno o mas campos vacios");
        }
        else
        {
            String sql="INSERT INTO PACIENTE (CEDULA,PRIMERNOMBRE,SEGUNDONOMBRE,PRIMERAPELLIDO,SEGUNDOAPELLIDO,PRIMERTELEFONO,SEGUNDOTELEFONO,FECHANACIMIENTO,EMAIL,DIRECCION)VALUES(?,?,?,?,?,?,?,?,?,?)";
               try {
            PreparedStatement pst = miConexion.Conectar().prepareStatement(sql);
            pst.setString(1,nuevoPaciente.getCedulaPaciente());
            pst.setString(2,nuevoPaciente.getpNombrePaciente());
            pst.setString(3,nuevoPaciente.getsNombrePaciente());
            pst.setString(4,nuevoPaciente.getpApellidoPaciente());
            pst.setString(5,nuevoPaciente.getsApellidoPaciente());
            pst.setString(6,nuevoPaciente.getpTelefonoPaciente());
            pst.setString(7,nuevoPaciente.getsTelefonoPaciente());
            pst.setString(8,nuevoPaciente.getFechaNacimientoPaciente());
            pst.setString(9,nuevoPaciente.getEmaiPaciente());
            pst.setString(10,nuevoPaciente.getDireccionPaciente());
            int n= pst.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null, "Datos Registrados Exitosamente");
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error Datos No Registrados");
            }
               }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error Datos No Registrados");
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
               }
        }
    }
    
    public void limpiarCampos(){
        txtCedulaPaciente.setText("");
        txtPNombrePaciente.setText("");
        txtSNombrePaciente.setText("");
        txtPApellidoPaciente.setText("");
        txtSApellidoPaciente.setText("");
        txtPTelefonoPaciente.setText("");
        txtSTelefonoPaciente.setText("");
        txtDireccionPaciente.setText("");
        txtEmailPaciente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPNombrePaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPApellidoPaciente = new javax.swing.JTextField();
        txtSNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSApellidoPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSTelefonoPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccionPaciente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCedulaPaciente = new javax.swing.JTextField();
        txtPTelefonoPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        jLabel1.setText("Primer Nombre");

        jLabel2.setText("Segundo Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        txtSApellidoPaciente.setToolTipText("");

        jLabel5.setText("Telefono 1");

        jLabel6.setText("Telefono 2");

        jLabel7.setText("Email");

        jLabel8.setText("Direccion");

        jLabel9.setText("Cedula");

        jLabel10.setText("Fecha Nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSApellidoPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtPApellidoPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSNombrePaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPNombrePaciente, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(btnAceptar))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailPaciente)
                            .addComponent(txtDireccionPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSTelefonoPaciente)
                            .addComponent(txtPTelefonoPaciente)))
                    .addComponent(btnCancelar)
                    .addComponent(jLabel10))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPTelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSTelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarPacienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarPacienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarPacienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarPacienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarPacienteJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCedulaPaciente;
    private javax.swing.JTextField txtDireccionPaciente;
    private javax.swing.JTextField txtEmailPaciente;
    private javax.swing.JTextField txtPApellidoPaciente;
    private javax.swing.JTextField txtPNombrePaciente;
    private javax.swing.JTextField txtPTelefonoPaciente;
    private javax.swing.JTextField txtSApellidoPaciente;
    private javax.swing.JTextField txtSNombrePaciente;
    private javax.swing.JTextField txtSTelefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
